### ISSUE TITLE
Using gr-bluetooth

### ISSUE THREAD

**Issue by 1am** [greatscottgadgets/gr-bluetooth#6]
Hi,

I've installed the gnuradio, gqrx and gr-bluetooth on a xubuntu VM. Everything seemed finish fine but after installation I got to a point where I wanted to test the while setup (specifically using gr-bluetooth with gqrx) but I couldn't find any reference on that. I launched the gnuration-companion as referenced in https://github.com/greatscottgadgets/gr-bluetooth/issues/5 but I couldn't see the bluetooth section as in the screenshot attached to the issue. So my questions are:
- What would be the next steps after installing everything to test it out if everything installed without errors?
- Is it remotely possible to use gqrx with gr-bluetooth for analyzing radio activity in 2.4GHz ISM band? Technically it seems feasible but maybe I'm missing something

**Comment by dominicgs** [comment]
gr-bluetooth is fairly old code which has been mostly untouched since 2009.  However, that doesn't mean that it won't work, but it may need some updating.

It is not designed to work with gqrx or gnuradio-companion, the only way to run it is using a standalone tool called `btrx`.  Running it from gqrx is something that you could add if you wish, I think it should be possible, but I don't know what would be required.

If you look in the samples/ directory, there are a few sample files, the manifest.txt file includes the command used to parse them.  I believe some of them should still work with the latest version of gnuradio.

**Comment by 1am** [comment]
Thank you Dominic. I'll see if I'll be able pull off with gqrx somehow :)
